-- Daikin product model mapping (from daikin-data.xlsx)
CREATE TABLE IF NOT EXISTS product_models (
  id         SERIAL PRIMARY KEY,
  model_no   TEXT NOT NULL,
  category   TEXT,
  type       TEXT,
  capacity   NUMERIC(6,2),
  unit       TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_product_models_model_no ON product_models (model_no);

INSERT INTO product_models (model_no, category, type, capacity, unit) VALUES
  ('FXFSQ25ARV16', 'INDOOR UNIT', 'Four Way Cassettes', 0.83, 'TON'),
  ('FXFSQ32ARV16', 'INDOOR UNIT', 'Four Way Cassettes', 1.04, 'TON'),
  ('FXFSQ40ARV16', 'INDOOR UNIT', 'Four Way Cassettes', 1.32, 'TON'),
  ('FXFSQ50ARV16', 'INDOOR UNIT', 'Four Way Cassettes', 1.65, 'TON'),
  ('FXFSQ63ARV16', 'INDOOR UNIT', 'Four Way Cassettes', 2.08, 'TON'),
  ('FXFSQ80ARV16', 'INDOOR UNIT', 'Four Way Cassettes', 2.65, 'TON'),
  ('FXFSQ100ARV16', 'INDOOR UNIT', 'Four Way Cassettes', 3.31, 'TON'),
  ('FXFSQ125ARV16', 'INDOOR UNIT', 'Four Way Cassettes', 4.15, 'TON'),
  ('FXFSQ140ARV16', 'INDOOR UNIT', 'Four Way Cassettes', 4.65, 'TON'),
  ('FXKQ32ARV16', 'INDOOR UNIT', 'One Way Cassettes', 1.04, 'TON'),
  ('FXKQ40ARV16', 'INDOOR UNIT', 'One Way Cassettes', 1.32, 'TON'),
  ('FXKQ50ARV16', 'INDOOR UNIT', 'One Way Cassettes', 1.65, 'TON'),
  ('FXKQ63ARV16', 'INDOOR UNIT', 'One Way Cassettes', 2.08, 'TON'),
  ('FXZQ20CRV16', 'INDOOR UNIT', 'Compact Cassette', 0.63, 'TON'),
  ('FXZQ25CRV16', 'INDOOR UNIT', 'Compact Cassette', 0.83, 'TON'),
  ('FXZQ32CRV16', 'INDOOR UNIT', 'Compact Cassette', 1.04, 'TON'),
  ('FXZQ40CRV16', 'INDOOR UNIT', 'Compact Cassette', 1.32, 'TON'),
  ('FXZQ50CRV16', 'INDOOR UNIT', 'Compact Cassette', 1.65, 'TON'),
  ('FXCQ25BVM6', 'INDOOR UNIT', 'Two Way Cassette', 0.83, 'TON'),
  ('FXCQ32BVM6', 'INDOOR UNIT', 'Two Way Cassette', 1.04, 'TON'),
  ('FXCQ40BVM6', 'INDOOR UNIT', 'Two Way Cassette', 1.32, 'TON'),
  ('FXCQ50BVM6', 'INDOOR UNIT', 'Two Way Cassette', 1.65, 'TON'),
  ('FXCQ63BVM6', 'INDOOR UNIT', 'Two Way Cassette', 2.08, 'TON'),
  ('FXCQ80BVM6', 'INDOOR UNIT', 'Two Way Cassette', 2.65, 'TON'),
  ('FXCQ125BVM6', 'INDOOR UNIT', 'Two Way Cassette', 4.15, 'TON'),
  ('BRC7M632F-6', 'INDOOR UNIT', 'Receiver-Four way cassettes', NULL, NULL),
  ('BRC63AV', 'INDOOR UNIT', 'Receiver-One way cassettes', NULL, NULL),
  ('BRC7M530W6', 'INDOOR UNIT', 'Receiver-Compact cassettes', NULL, NULL),
  ('BRC7M65', 'INDOOR UNIT', 'Receiver-Two way  cassettes', NULL, NULL),
  ('BRC4M150W16', 'INDOOR UNIT', 'Remote -Four way cassettes', NULL, NULL),
  ('BRC4M150W17', 'INDOOR UNIT', 'Remote -One way cassettes', NULL, NULL),
  ('BRC4M150W18', 'INDOOR UNIT', 'Remote -Compact cassettes', NULL, NULL),
  ('BYCQ125EAF6', 'INDOOR UNIT', 'Panel-Four way cassettes', NULL, NULL),
  ('BYKQ63AW', 'INDOOR UNIT', 'Panel-One way cassettes', NULL, NULL),
  ('BYFQ60CBW6', 'INDOOR UNIT', 'Panel-Compact cassettes', NULL, NULL),
  ('BYBCQ40CF', 'INDOOR UNIT', 'Panel-Two way cassettes', NULL, NULL),
  ('BYBCQ63CF', 'INDOOR UNIT', 'Panel-Two way cassettes', NULL, NULL),
  ('BYBCQ125CF', 'INDOOR UNIT', 'Panel-Two way cassettes', NULL, NULL),
  ('FXAQ20ARVE6', 'INDOOR UNIT', 'HI WALLS', 0.63, 'TON'),
  ('FXAQ25ARVE6', 'INDOOR UNIT', 'HI WALLS', 0.83, 'TON'),
  ('FXAQ32ARVE6', 'INDOOR UNIT', 'HI WALLS', 1.04, 'TON'),
  ('FXAQ40ARVE6', 'INDOOR UNIT', 'HI WALLS', 1.32, 'TON'),
  ('FXAQ50ARVE6', 'INDOOR UNIT', 'HI WALLS', 1.65, 'TON'),
  ('FXAQ63ARVE6', 'INDOOR UNIT', 'HI WALLS', 2.08, 'TON'),
  ('FXAQ71BRV16', 'INDOOR UNIT', 'HI WALLS', 2.5, 'TON'),
  ('FXAQ80ARV16', 'INDOOR UNIT', 'HI WALLS', 2.65, 'TON'),
  ('FXAQ90ARV16', 'INDOOR UNIT', 'HI WALLS', 3, 'TON'),
  ('FXDQ20PDV36', 'INDOOR UNIT', 'Low Static Ductable', 0.63, 'TON'),
  ('FXDQ25PDV36', 'INDOOR UNIT', 'Low Static Ductable', 0.83, 'TON'),
  ('FXDQ32PDV36', 'INDOOR UNIT', 'Low Static Ductable', 1.04, 'TON'),
  ('FXDQ40PDV36', 'INDOOR UNIT', 'Low Static Ductable', 1.32, 'TON'),
  ('FXDQ50PDV36', 'INDOOR UNIT', 'Low Static Ductable', 1.65, 'TON'),
  ('FXDQ63PDV36', 'INDOOR UNIT', 'Low Static Ductable', 2.08, 'TON'),
  ('FXMQ40ARV16', 'INDOOR UNIT', 'Mid Static Ductable', 1.32, 'TON'),
  ('FXMQ50ARV16', 'INDOOR UNIT', 'Mid Static Ductable', 1.65, 'TON'),
  ('FXMQ63ARV16', 'INDOOR UNIT', 'Mid Static Ductable', 2.08, 'TON'),
  ('FXMQ80ARV16', 'INDOOR UNIT', 'Mid Static Ductable', 2.65, 'TON'),
  ('FXMQ100ARV16', 'INDOOR UNIT', 'Mid Static Ductable', 3.31, 'TON'),
  ('FXMQ20PBV36', 'INDOOR UNIT', 'High Static Ductable', 0.63, 'TON'),
  ('FXMQ25PBV36', 'INDOOR UNIT', 'High Static Ductable', 0.83, 'TON'),
  ('FXMQ32PBV36', 'INDOOR UNIT', 'High Static Ductable', 1.04, 'TON'),
  ('FXMQ40PBV36', 'INDOOR UNIT', 'High Static Ductable', 1.32, 'TON'),
  ('FXMQ50PBV36', 'INDOOR UNIT', 'High Static Ductable', 1.65, 'TON'),
  ('FXMQ63PBV36', 'INDOOR UNIT', 'High Static Ductable', 2.08, 'TON'),
  ('FXMQ80PBV36', 'INDOOR UNIT', 'High Static Ductable', 2.65, 'TON'),
  ('FXMQ100PBV36', 'INDOOR UNIT', 'High Static Ductable', 3.31, 'TON'),
  ('FXMQ125PBV36', 'INDOOR UNIT', 'High Static Ductable', 4.15, 'TON'),
  ('FXMQ140PBV36', 'INDOOR UNIT', 'High Static Ductable', 4.65, 'TON'),
  ('FXMQ170NVE6', 'INDOOR UNIT', 'High Static Ductable', 5.5, 'TON'),
  ('FXMQ200NVE6', 'INDOOR UNIT', 'High Static Ductable', 6.3, 'TON'),
  ('FXMQ250NVE6', 'INDOOR UNIT', 'High Static Ductable', 8.3, 'TON'),
  ('BRC7N618-6', 'INDOOR UNIT', 'Receiver - Hi walls', NULL, NULL),
  ('BRC4M150W16', 'INDOOR UNIT', 'Remote - Hi walls', NULL, NULL),
  ('BRC4M61-6', 'INDOOR UNIT', 'Receiver- Low Static Ductable', NULL, NULL),
  ('BRC4M61-6', 'INDOOR UNIT', 'Receiver-  Mid Static Ductable', NULL, NULL),
  ('BRC4M61-6', 'INDOOR UNIT', 'Receiver-  High Static Ductable', NULL, NULL),
  ('BRC4M150W16', 'INDOOR UNIT', 'Remote - Hi walls', NULL, NULL),
  ('BRC4M150W16', 'INDOOR UNIT', 'Remote - Low Static Ductable', NULL, NULL),
  ('BRC4M150W16', 'INDOOR UNIT', 'Remote - Mid Static Ductable', NULL, NULL),
  ('BRC4M150W16', 'INDOOR UNIT', 'Remote - High Static Ductable', NULL, NULL),
  ('RXQ6BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 6, 'HP'),
  ('RXQ8BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 8, 'HP'),
  ('RXQ10BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 10, 'HP'),
  ('RXQ12BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 12, 'HP'),
  ('RXQ14BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 14, 'HP'),
  ('RXQ16BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 16, 'HP'),
  ('RXQ18BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 18, 'HP'),
  ('RXQ20BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 20, 'HP'),
  ('RXQ22BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 22, 'HP'),
  ('RXQ24BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 24, 'HP'),
  ('RXQ26BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - Single', 26, 'HP'),
  ('RXQ28BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 14+14', 28, 'HP'),
  ('RXQ30BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 12+18', 30, 'HP'),
  ('RXQ32BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 14+18', 32, 'HP'),
  ('RXQ34BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 16+18', 34, 'HP'),
  ('RXQ36BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 18+18', 36, 'HP'),
  ('RXQ38BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 14+24', 38, 'HP'),
  ('RXQ40BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 14+26', 40, 'HP'),
  ('RXQ42BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 18+24', 42, 'HP'),
  ('RXQ44BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 18+26', 44, 'HP'),
  ('RXQ46BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 22+24', 46, 'HP'),
  ('RXQ48BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 24+24', 48, 'HP'),
  ('RXQ50BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 24+26', 50, 'HP'),
  ('RXQ52BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 26+26', 52, 'HP'),
  ('RXQ54BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 18+18+18', 54, 'HP'),
  ('RXQ56BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 12+18+26', 56, 'HP'),
  ('RXQ58BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 14+18+26', 58, 'HP'),
  ('RXQ60BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 18+18+24', 60, 'HP'),
  ('RXQ62BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 18+18+26', 62, 'HP'),
  ('RXQ64BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 12+26+26', 64, 'HP'),
  ('RXQ66BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 18+24+24', 66, 'HP'),
  ('RXQ68BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 18+24+26', 68, 'HP'),
  ('RXQ70BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 18+26+26', 70, 'HP'),
  ('RXQ72BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 24+24+24', 72, 'HP'),
  ('RXQ74BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 24+24+26', 74, 'HP'),
  ('RXQ76BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 24+26+26', 76, 'HP'),
  ('RXQ78BRY16', 'OUTDOOR UNIT', 'Cooling only/Top discharge - 26+26+26', 78, 'HP'),
  ('RXQ6BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 6, 'HP'),
  ('RXQ8BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 8, 'HP'),
  ('RXQ10BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 10, 'HP'),
  ('RXQ12BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 12, 'HP'),
  ('RXQ14BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 14, 'HP'),
  ('RXQ16BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 16, 'HP'),
  ('RXQ18BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 18, 'HP'),
  ('RXQ20BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 20, 'HP'),
  ('RXQ22BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 22, 'HP'),
  ('RXQ24BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 24, 'HP'),
  ('RXQ26BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - Single', 26, 'HP'),
  ('RXQ28BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 14+14', 28, 'HP'),
  ('RXQ30BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 12+18', 30, 'HP'),
  ('RXQ32BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 14+18', 32, 'HP'),
  ('RXQ34BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 16+18', 34, 'HP'),
  ('RXQ36BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 18+18', 36, 'HP'),
  ('RXQ38BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 14+24', 38, 'HP'),
  ('RXQ40BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 14+26', 40, 'HP'),
  ('RXQ42BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 18+24', 42, 'HP'),
  ('RXQ44BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 18+26', 44, 'HP'),
  ('RXQ46BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 22+24', 46, 'HP'),
  ('RXQ48BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 24+24', 48, 'HP'),
  ('RXQ50BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 24+26', 50, 'HP'),
  ('RXQ52BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 26+26', 52, 'HP'),
  ('RXQ54BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 18+18+18', 54, 'HP'),
  ('RXQ56BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 12+18+26', 56, 'HP'),
  ('RXQ58BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 14+18+26', 58, 'HP'),
  ('RXQ60BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 18+18+24', 60, 'HP'),
  ('RXQ62BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 18+18+26', 62, 'HP'),
  ('RXQ64BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 12+26+26', 64, 'HP'),
  ('RXQ66BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 18+24+24', 66, 'HP'),
  ('RXQ68BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 18+24+26', 68, 'HP'),
  ('RXQ70BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 18+26+26', 70, 'HP'),
  ('RXQ72BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 24+24+24', 72, 'HP'),
  ('RXQ74BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 24+24+26', 74, 'HP'),
  ('RXQ76BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 24+26+26', 76, 'HP'),
  ('RXQ78BRY16', 'OUTDOOR UNIT', 'Heat Pump/Top discharge - 26+26+26', 78, 'HP'),
  ('RXMQ4BRV16', 'OUTDOOR UNIT', 'Cooling Only/Side Discharge', 4, 'HP'),
  ('RXMQ5BRV16', 'OUTDOOR UNIT', 'Cooling Only/Side Discharge', 5, 'HP'),
  ('RXMQ6BRV16', 'OUTDOOR UNIT', 'Cooling Only/Side Discharge', 6, 'HP'),
  ('RXMQ8BRV16', 'OUTDOOR UNIT', 'Cooling Only/Side Discharge', 8, 'HP'),
  ('RXMQ10BRV16', 'OUTDOOR UNIT', 'Cooling Only/Side Discharge', 10, 'HP'),
  ('RXMQ12BRV16', 'OUTDOOR UNIT', 'Cooling Only/Side Discharge', 12, 'HP'),
  ('KHRP26A22T6', 'REFNETS', 'Refnets - 22T', NULL, NULL),
  ('KHRP26A33T6', 'REFNETS', 'Refnets - 33T', NULL, NULL),
  ('KHRP26A72T6', 'REFNETS', 'Refnets - 72T', NULL, NULL),
  ('KHRP26A73T6', 'REFNETS', 'Refnets - 73T', NULL, NULL);
